// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp8_ww4_nez_MClt-NOrxOk82Hf7TMG6A',
    appId: '1:644959023893:web:28ab731861add98e73ef1c',
    messagingSenderId: '644959023893',
    projectId: 'iot-chong-trom-xe-may',
    authDomain: 'iot-chong-trom-xe-may.firebaseapp.com',
    databaseURL: 'https://iot-chong-trom-xe-may-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-chong-trom-xe-may.firebasestorage.app',
    measurementId: 'G-RT006GEF2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JEvyaWmNu-b2lPZ_tJg6WNCRzY3G9rc',
    appId: '1:644959023893:android:b1e2cb8485bfd38873ef1c',
    messagingSenderId: '644959023893',
    projectId: 'iot-chong-trom-xe-may',
    databaseURL: 'https://iot-chong-trom-xe-may-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-chong-trom-xe-may.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIIT3EqAPjgwOV2OLRhViPrOHAVeZLYxk',
    appId: '1:644959023893:ios:24891f9a6b5c934673ef1c',
    messagingSenderId: '644959023893',
    projectId: 'iot-chong-trom-xe-may',
    databaseURL: 'https://iot-chong-trom-xe-may-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-chong-trom-xe-may.firebasestorage.app',
    iosBundleId: 'com.example.webFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIIT3EqAPjgwOV2OLRhViPrOHAVeZLYxk',
    appId: '1:644959023893:ios:24891f9a6b5c934673ef1c',
    messagingSenderId: '644959023893',
    projectId: 'iot-chong-trom-xe-may',
    databaseURL: 'https://iot-chong-trom-xe-may-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-chong-trom-xe-may.firebasestorage.app',
    iosBundleId: 'com.example.webFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDicr5ZKJVqiIZhXOArU6NYesMmtnvZmKo',
    appId: '1:644959023893:web:7f3a019022a38ded73ef1c',
    messagingSenderId: '644959023893',
    projectId: 'iot-chong-trom-xe-may',
    authDomain: 'iot-chong-trom-xe-may.firebaseapp.com',
    databaseURL: 'https://iot-chong-trom-xe-may-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-chong-trom-xe-may.firebasestorage.app',
    measurementId: 'G-SBPWJE6RP6',
  );
}
